import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Image from "next/image";

import SmoothScroll from "@/components/SmoothScroll"
import ScrollTrigger from "gsap-trial/ScrollTrigger";
import { gsap } from "gsap/dist/gsap";
const playfair = Playfair_Display({ subsets: ["latin"] });



// ScrollTrigger.create({
//   animation:gsap.from(".logo", {
//     y:"50vh",
//     scale: 6,
//     yPercent: -50,
//   }),
//   scrub: true,
//   trigger:".content",
//   start: "top bottom",
//   endTrigger: ".content",
//   end: "top center",

// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        <SmoothScroll>
        <div className="nav fixed w-full h-24 flex items-center justify-between px-0 py-4 z-50">
          <div className="items-left ml-10">
            <a className="no-underline font-bold  px-5 py-2 text-base border border-black rounded-full transition ease-out hover:bg-slate-100 gap-5" href="#">kuliner</a>
            <a className="no-underline font-bold  px-5 py-2 text-base border border-black rounded-full transition ease-out hover:bg-slate-100" href="">etnis</a>
          </div>
          <div className="items-right mr-10">
            <a className="no-underline font-bold  px-5 py-2 text-base border border-black rounded-full transition ease-out hover:bg-slate-100" href="#">peta</a>
            <a className="no-underline font-bold  px-5 py-2 text-base border border-black rounded-full transition ease-out hover:bg-slate-100" href="#">agama</a>
          </div>
        </div>
        <div className="logo-container fixed top-0 left-1/2 -translate-x-1/2 p-6 z-50">
          <Image
          src="/nusantara.svg"
          width={200}
          height={200}
          className="logo"
          />
        </div>
        <div className="container w-full h-screen"></div>
      
        {children}
        </SmoothScroll>
        </body>
    </html>
  );
}
